src/cdi-ii/0002-norma-topologia.md
=> [CDI2] Fix wrong variable on example

src/cdi-ii/0003-funcoes-continuidade.md
Fixed typo in the examples of continuity.
Fixed typo in the examples of limits.
=> [CDI2] Fixed typos in examples on page 3

src/lp/0001-conceitos-gerais.md
=> [LP] Add space after ,

src/lp/0003-logica-proposicional-sc.md
Cardoso ain't the only one fixing typos
=> [LP] Fix typo

src/cdi-ii/0003-funcoes-continuidade.md
F for @diogotcorreia who forgot TeX commands
=> [CDI-II] fix typo

src/md/0007-funcoesgeradoras.md
A imagem embedded na linha 23 e a equação na linha 27-29 estavam trocadas.
=> [MD] Aula 5 - Imagens trocadas

package.json, src/.vuepress/config.js, yarn.lock
This PR updates packages in order to fix this issue.
=> Fix Latex not working on some pages

src/.vuepress/config.js, src/lp/0007-prolog-intro.md, src/lp/0008-prolog-mid.md
Still missing a few parts, but has valuable additions/typos fixed
=> [LP] Add Aula 11 - still missing some things

src/.vuepress/components/KatexElement.vue, src/.vuepress/components/fft-calculator.vue, src/.vuepress/config.js, src/md/tools/fft-calculator.md
=> [MD] FFT step-by-step calculator

src/.vuepress/components/bezout-calculator.vue, src/.vuepress/config.js, src/md/tools/bezout-calculator.md
=> [MD] Add Bézout calculator

src/cdi-ii/exercicios/fichas-aulas-praticas.md
=> [CDI2] Fix typo in fichas-aulas-praticas page

src/md/0011-FFT.md, src/md/0012-MDC.md, src/md/0013-calendario.md, src/md/0014-pascoa.md, src/md/0015-congruencias.md, src/md/0016-chines-restos.md, src/md/0017-rsa.md
not sure about any of this, please review properly
=> [MD] fix typo & add clarity

src/cdi-ii/0013-funcao-inversa.md
Adds examples about "Função Inversa" and "Função Implícita"
=> [CDI2] Add content from week 8 (half 1)

src/.vuepress/components/calendar-calculator.vue, src/.vuepress/config.js, src/md/tools/calendar-calculator.md
=> [MD] Add calendar calculator

src/cdi-ii/0014-variedades.md
mais um typo, que vergonha
#LeicShit
=> [CDI2] Fix typo

src/cdi-ii/0014-variedades.md
=> [CDI2] Add content from week 9 (half 1)

src/cdi-ii/0002-norma-topologia.md
=> [CDI-II] Fix typo (fix #243)

src/md/0020-labirintos.md
=> [MD] add teorema de lucas

src/cdi-ii/0016-campos-vetoriais.md
Olá, tinhas um "que" a mais.
#LeicShit
=> [CDI2] Fix typo campos vetoriais

src/md/0023-teoriadofluxo.md
honestly i'm fine with you rejecting this pr
call it a feature not a bug
=> [MD] fix typo

content/index.md
=> [Meta] Remove Rúben Nobre's Notion from "Links úteis"

content/fp/exercises/0001-ficha-pavao.md
=> [FP] Add Pavao exercises + solution

content/cdi-iii/0004-equacoes-exatas.md
=> [CDI3] Fix typo

content/fp/exercises/0001-ficha-pavao.md
The new version does not work for lists with length 0 but that is how the reduce function works
=> [FP] Fix exercise 4.c), chapter 6.2

content/index.md
The "Criador de Horários" has a new domain.
=> [Meta] Update link and description for "Criador de Horários" 

content/cdi-iii/1001-laplace-cheat.md, content/index.md
Usado nos exercicio 3.d) na semana 5.2
=> [CDI3] Add entry `t^n e^at` to Transformada de Laplace (Cheat Sheet)

content/asa/0005-caminhos-mais-curtos.md
I'll mark this as ready when I've finished reading the whole page
=> [ASA] Fix typos on shortest paths page

content/ges/0005-analise-projetos-investimento.md
Clarify some ideas and fix typos
=> [Ges] Fix typos and other small changes

content/asa/exercicios/0001-fichas-2021-2022.md
=> [ASA] Fix exercise drive links

content/asa/1001-algoritmos-sheet.md
=> [ASA] Add algorithms cheat sheet

src/styles/markdown.css
=> Center markdown images

content/fis-i/0002-kinematics-2d.md
=> [Fis1] Fix typos

content/tc/0001-linguagens-e-automatos.md
... e Linguagens Independentes do Contexto.
=> [TC] Add Expressões Regulares. Lema de Pumping. Autómatos de Pilha. Linguagens Independentes do Contexto

content/cdi-iii/0001-equacoes-diferenciais-ordinarias.md
=> [CDI3] Fix typo on non homogenous case for ODEs

content/tc/0003-teoria-da-computabilidade.md
=> [TC] Add computability theory chapter

content/tc/0002-maquinas-de-turing.md
Co-authored-by: Rafael Oliveira <rafdev.x@gmail.com>
=> [TC] Fix typo

content/cdi-iii/0001-equacoes-diferenciais-ordinarias.md, content/ges/0003-ambiente-economico.md, content/md/0009-combinatorio.md, content/md/0013-calendario.md, content/so/0002-files.md, content/so/0003-filesystem.md, content/so/0007-comunicacao.md, content/so/0010-memory-management.md, content/tc/0001-linguagens-e-automatos.md, content/tc/0002-maquinas-de-turing.md, content/tc/0003-teoria-da-computabilidade.md
=> [TC] [MD] [Ges] [SO] [CDI3] Fix typos

content/ipm/0007-analise-qualitativa.md
linha 41 estava meio estranha portanto mudei um pouco a frase toda em vez de corrigir o typo.
=> [IPM] Fix typos and clarify

.github/CODEOWNERS, content/index.md
@randomicecube is now a CODEOWNER and main maintainer for IAED
=> Update contributors and CODEOWNER for IAED

content/iaed/assets/1001-simp-lig.c
=> Fix mallocs in insertEnd

.github/CODEOWNERS
=> Set @Calhau18 as CODEOWNER for PE and TC

content/fis-i/exercicios/0999-fichas-2021-2022.md
=> [Fis1] Add solutions to Quizzes 14/15 and TP12 (2021-2022)

content/tc/0001-linguagens-e-automatos.md, content/tc/0002-maquinas-de-turing.md, content/tc/0003-teoria-da-computabilidade.md, content/tc/0004-complexidade-computacional.md
- [TC] Emphasizing definition of equivalence of Turing machines.
- [TC] Emphasizing relevant content on 3rd chapter.
=> [TC] Further reviewing and cleanup

content/index.md
=> [Meta] Add liability disclaimer

src/components/Dialog/Dialog.js, src/components/SearchBar/SearchBar.js, src/hooks/useViewHeightCSS.js
=> Only listen to resize events when a dialog is open

.github/CODEOWNERS, content/index.md
=> [Meta] Update contributors and CODEOWNERs for IA and BD

.github/labeler.yml
=> Update labeler config with IA and EMD configurations

content/bd/0002-sql.md
=> [BD] Add Introduction to SQL

content/ia/0002-resolucao-procura.md
=> [IA] Fix typos

content/ia/0001-agentes.md, content/ia/0002-resolucao-procura.md
=> [IA] Fix typos and improve wording

content/ia/0003-procura-informada.md
=> [IA] Fix typos and improve wording on the Informed Search page

content/bd/0003-er-model.md
=> [BD] Fix typos and improve wording on the ER Model page

content/index.md, content/pe/guides/0001-r-setup.md
=> [PE] Fix typo

content/ia/0004-satisfacao-restricoes.md
=> [IA] Fix typos - third week

content/pe/0001-nocoes-basicas.md
- Add footer to all pages (#700)
- Replace GitHub repo links with new organization link (#702)
- Link contributing documentation on README and homepage (#707)
- Add Code of Conduct (#706)
- Add pull request template and edit issue templates (#708)
- [TC] Fix typos and clarify chapter 2 (#703)
- [TC] Restructure Universal Machine section (#705)
- [TC] Fix typos and formatting (#704)
- [IPM] Add content from week 6 (#701)
- Update footer contribution guide link (#709)
- [TC] Cleanup and add missing examples to first chapter (#699)
- Move pull request template to correct location (#710)
- [PE] Add Combinações Lineares de VA (#698)
- [PE] Add joint probability distribution (#697)
- Set @Calhau18 as CODEOWNER for PE and TC (#712)
- [Fis1] Add solutions to Quizzes 14/15 and TP12 (2021-2022) …
=> [PE] Add simple explanation to discrete and continuous intervals

content/ia/0004-satisfacao-restricoes.md
=> [IA] fix typo

content/ia/0004-satisfacao-restricoes.md
=> [IA] Fix misunderstandings in AC-3 example

content/bd/0005-relational-algebra.md
=> [BD] Fix typos and clarify

content/bd/0003-er-model.md
=> [BD] Improve explanation of Weak Entities

src/styles/themes/nord.css
=> Fix Nord theme being applied by default

content/bd/0006-advanced-sql.md
=> [BD] Add Advanced SQL

content/pe/0003-va-discretas.md, content/pe/0004-va-continuas.md
=> [PE] Sort distributions to the order given in class

content/pe/0003-va-discretas.md, content/pe/0006-comb-lineares-de-va.md, content/pe/0007-estimacao-pontual.md, content/pe/0008-estimacao-por-intervalos.md, content/pe/0009-teste-de-hipoteses.md
=> [PE] Add warnings to non lectured content

.github/CODEOWNERS
=> Change PE codeowner to @Pesteves2002

content/bd/guides/0100-running-cgi-files-locally.md
=> [BD] Improve wording and fix typo on the CGI Guide page

src/styles/main.css, src/styles/markdown.css, src/styles/themes/black.css, src/styles/themes/nord.css, src/styles/themes/solarized.css
=> Change styling of links

content/pe/0009-teste-de-hipoteses.md
O rocha disse que devia ser assim no discord (consegues ver no #PE) mas convém rever a ver se está bem
=> [PE] Fix wrong hypothesis values

content/pe/0005-distribuicoes-conjuntas.md, content/pe/0010-regressao-linear.md
=> [PE] Add regressao linear page and fix typo

gatsby-config.js
Update symbol according to latest comment on https://github.com/KaTeX/KaTeX/issues/2167#issuecomment-1168350409
=> Update identity symbol with a better approximation

content/al/0502-valores-vetores-proprios.md, content/apre/index.md, content/asa/0001-introducao.md, content/asa/0003-tecnicas-algoritmos.md, content/emd/0002-principio-pombal.md, content/emd/0003-mdc-eq-diofantinas.md, content/emd/0005-teorema-chines-restos.md, content/emd/0006-rsa.md, content/emd/0009-grafos.md, content/emd/0012-fft.md, content/emd/archive/0007-teorema-de-newton.md, content/emd/archive/0008-calculo-combinatorio.md, content/emd/archive/0010-pascoa.md, content/emd/archive/0012-relacionamentos-gale-shapley.md, content/emd/archive/0013-teoria-fluxo.md, content/emd/archive/0016-automatos-finitos.md, content/emd/cheatsheets/0001-mdc-cheat.md, content/emd/cheatsheets/0003-grafos.md, content/emd/exercicios/0999-fichas-2020-2021.md, content/iaed/0004-tabelas.md, content/so/0003-filesystem.md
Pls help me from my EMD sufferingations
=> [AL/Apre/ASA/EMD/IAED/SO] Fix various typos

gatsby-config.js
=> Rename Umami script path

content/bd/0006-advanced-sql.md
Fixed incorrection in BD > Advanced SQL
=> [BD] Fix minor incorrection

content/iac/0002-mundo-binario.md
=> [IAC] Fix wrong values in binary tables

content/bd/0001-intro-dbms.md, content/bd/0002-sql.md, content/bd/0003-er-model.md, content/bd/0004-relational-model-conversion.md, content/bd/0006-advanced-sql.md, content/bd/0007-normalization.md
=> [BD] Fix typos

content/fp/exercises/0001-ficha-pavao.md
=> [FP] Remove solution student name

content/ges/0005-analise-projetos-investimento.md
Add the missing backslashes before the percentage symbols in the example's last question
=> [Ges] Add missing backslashes

content/ams/index.md, content/apre/index.md, content/cg/index.md, content/comp/index.md, content/es/index.md, content/oc/index.md, content/rc/index.md, content/sd/index.md
=> Add link to 3rd year UCs

content/al/0001-introducao.md, content/al/0002-operacoes-matrizes.md, content/al/0003-determinantes.md, content/al/index.md
=> [AL] Add beginning content

content/apre/0001-machine-learning.md
=> [Apre] Add machine learning content

content/oc/0001-metricas-performance.md
- Fix typos and pontuation;
- Improve wording and cohesion;
- Change some text style.
=> [OC] Overall fix on the Performance Metrics page

plugins/gatsby-remark-post-image-data/index.js, plugins/gatsby-remark-pre-image-data/index.js, src/styles/markdown.css
Fixes #844 
There were actually two issues:
- Non SVG images lost their filters if they had a captions
- SVG images didn't show their caption at all
Both these issues are fixed by this PR
=> Fix broken image caption support

gatsby-config.js, plugins/gatsby-remark-post-image-data/index.js, plugins/gatsby-remark-pre-image-data/index.js, src/styles/main.css, src/styles/markdown.css
=> Render SVGs as object instead of img

content/oc/0001-metricas-performance.md
=> [OC] Add FLOPS metric and Amdahl's Law Example

gatsby-config.js
=> Add MIPS Assembly syntax highlighting to Prism.js

content/index.md
=> [Meta] Add João Rodrigues to contributors

content/fis-ii/exercicios/0001-fichas-2021-2022.md
=> [Fis-II] Remove borked links

content/oc/exercicios/9999-fichas-2022-2023.md
=> [OC] Add more exercise solutions by @constancadcunha

content/oc/0002-linguagem-computador.md
- Fix mistakes;
- Fix typos and punctuation;
- Improve wording and cohesion;
- Add information;
- Change some text style.
=> [OC] Overall fix on the Computer Language page

content/asa/index.md, content/cdi-iii/index.md, content/fis-ii/index.md, content/ges/index.md, content/ipm/index.md, content/po/index.md, content/so/index.md, content/tc/index.md
=> [META] Remove UC links that are outdated

content/apre/index.md
=> [APRE] Fix content explanation

content/cdi-ii/exercicios/fichas-aulas-praticas.md, content/cdi-iii/index.md
=> [Meta] Remove broken Edenbox links

content/ieco/index.md
=> [IEco] Add course explanation

content/emd/0012-fft.md
=> [EMD] Add FFT youtube video

content/apre/0007-lazy-learning.md
=> [Apre] Clarify Minkowski distance function

content/apre/exercicios/fichas-aulas-praticas.md
=> [Apre] Add exercise resolutions by Hugo Silva

content/oc/exercicios/9999-fichas-2022-2023.md
=> [OC] Add ficha 9 and 10 solutions by @constancadcunha

CONTRIBUTING.md, README.md, content/index.md, content/oc/0004-memoria-caches.md, content/oc/0005-memoria-virtual.md, gatsby-config.js
Regarding https://github.com/leic-pt/docs/pull/2
=> Update contribution docs links to new domain

src/styles/markdown.css
=> Hide link styles on Gatsby images

content/apre/cheatsheets/0001-cheatsheet-exame.md
Thank you @randomicecube and @Rafael-R!
=> [Apre] Add exam cheatsheets by @randomicecube and @Rafael-R

src/styles/markdown.css
=> Fix MathJax not displaying in draw.io SVGs

content/ges/0005-analise-projetos-investimento.md
Temos de adicionar as Amortizações/Depreciações e não subtrair
=> [Ges] Fix incorrect cash flow formula

content/rc/0005-ligacao-dados.md
=> [RC] Fix Typo

src/components/PageLayout.js, src/components/icons/Edit.js, src/styles/main.css
Adds an edit button at the top of each page, linking directly to the edit page of the respective markdown file on GitHub.
=> Add edit button

src/components/ExternalLink.js, src/components/PageLayout.js
=> Open edit page on new tab

content/rc/0001-introducao.md
=> [RC] Fix typos and clarify example

src/styles/main.css
=> Fix mermaid diagrams not being inverted on dark mode

content/rc/0005-ligacao-dados.md
=> [RC] Fix small typo on exercise

content/rc/0004-rede.md
na linha 475 é 15 ou devia ser 16 já que o máximo é 16?
=> [RC] Fix typos and rewording

content/rc/0005-ligacao-dados.md
linhas 227 e 248 são iguais de propósito ou é repetição? 
parte 1 pq ainda não acabei de ver a página toda, só vi metade
=> [RC] Fix typos in data link layer page

content/rc/0003-transporte.md
=> [RC] Fix typos in transport layer page

content/rc/guides/0001-terminologia.md
=> [RC] Add layer terminology comparison table

content/rc/0005-ligacao-dados.md
=> [RC] Fix some typos

content/rc/0003-transporte.md, content/rc/0005-ligacao-dados.md
=> [RC] Fix typo in CSMA/CA

content/rc/index.md
=> [RC] Remove no content warning

content/rc/0002-aplicacao.md, content/rc/0003-transporte.md, content/rc/0004-rede.md, content/rc/0005-ligacao-dados.md
=> [RC] Fix typos

content/rc/0005-ligacao-dados.md
=> [RC] Fix small typo in Datalink layer content

content/rc/0005-ligacao-dados.md
=> [RC] Finish incomplete example

content/rc/0001-introducao.md, content/rc/0002-aplicacao.md, content/rc/0003-transporte.md, content/rc/0004-rede.md, content/rc/0005-ligacao-dados.md
- Fix typos and punctuation;
- Improve wording and cohesion;
- Change some text style;
- Correct verb conjugations and gender of pronouns/noun determiners;
- Add a few tidbits.
=> [RC] Overall fix on all course pages

content/index.md
=> [Meta] Add @jjasferreira as RC contributor

content/index.md
=> [Meta] Update contributors list

content/oc/0001-metricas-performance.md, content/oc/0002-linguagem-computador.md, content/oc/0003-papel-compilador.md, content/oc/0004-memoria-caches.md, content/oc/0005-memoria-virtual.md
=> [OC] Fix typos and improve clarity

.gitignore, flake.lock, flake.nix
=> Add flake.nix environment

content/index.md, src/components/ThemeSettings/ThemeSettings.js, src/hooks/theme-hooks.js, src/styles/themes/gruvbox.css
=> Add Gruvbox theme

.github/workflows/prettier.yml
There was a bug in 4.2 (due to a NPM update) that prevented it from working: https://github.com/creyD/prettier_action/issues/113
=> chore: update prettier action version to 4.3

content/asa/0010-string-matching.md, content/asa/1001-algoritmos-sheet.md
=> [ASA] Add String Matching content

content/sd/0001-introducao.md, content/sd/index.md
=> [SD] Add introdução

content/pe/0006-comb-lineares-de-va.md
https://www.youtube.com/watch?v=zeJD6dqJ5lo
=> [PE] Add 3b1b's video about the Central Limit Theorem

content/tc/0002-maquinas-de-turing.md
=> [TC] Fix Prova Turing Machines Unidirecionais equivalentes a Bidirecionais

content/es/0001-agile.md, content/es/index.md
=> [ES] Add Agile content

content/sd/0002-apis-de-comunicacao.md
Não quero resumir isto por enquanto, mas assim fica já um placeholder com as referências relevantes para quem quiser estudar.
Só faz sentido dar merge disto depois de #951
=> [SD] Add placeholder for apis de comunicação

content/sd/0001-introducao.md, content/sd/0003-tempo-e-sincronizacao.md
=> [SD] Fix typos

content/apre/0012-dimensionality-reduction.md
=> [Apre] Fix typos

content/pe/0007-estimacao-pontual.md, content/pe/0008-estimacao-por-intervalos.md
Hey! These exercises were 🌟 _inspired_ 🌟 from [here](https://fenix.tecnico.ulisboa.pt/downloadFile/1970943312382245/2023-01-25-Resolucao-Exame1.pdf).
Lmk if it's bad policy linking to this website
=> [PE] Add exercise examples to Estimação Pontual e Estimação Intervalar

content/ia/0002-procura-cega.md, content/ia/imgs/0002-bidirectional-search.svg
=> [IA] Add Bi-Directional Search content

content/index.md
=> Add project portfolios

content/lp/0014-lpo-semantico.md, package.json, src/components/md-tools/CalendarCalculator.js, src/components/md-tools/FFTCalculator.js, yarn.lock
=> chore: update prettier to 3.0.0

content/so/index.md
=> [SO] Add cpu.land resource link

content/cdi-i/0007-continuidade-limites.md
=> [CDI-I] Fix typo

content/rc/0002-aplicacao.md
=> [RC] Fix wrong IPv6 number of bits (it is 128 instead of 256)

content/apre/0008-linear-regression.md
From the slides, with j=0 it adds the bias param
=> [Apre] Fix typo

content/apre/0009-regression-model-evaluation.md
=> [Apre] Fix typo on page title

content/ges/0004-informacao-financeira.md
=> [Ges] Fix typo in LaTeX formula

content/iaed/0013-ponteiros.md
=> [IAED] Fix typo

content/rc/0004-rede.md
=> [RC] DHCP port information correction

content/rc/index.md
=> [RC] Add JimKurose's YT channel to RC's resources

content/rc/0003-transporte.md
=> [RC] Fix typo on transport layer

content/rc/0004-rede.md
=> [RC] Fix DHCP Address Leasing

content/rc/0003-transporte.md
I tried to clarify the explanation because I think the phrasing was a bit misleading. I think it would be ideal to showcase the TCP State Machine found in the classes slides, as it is explains the states more clearly than any text ever could
=> [RC] Add more information to Fast Recovery

content/apre/index.md
=> [Apre] Add link to Resumos do Calhau

content/apre/cheatsheets/0001-cheatsheet-exame.md
=> [Apre] Fix broken link to cheat sheet

content/sd/index.md
=> [SD] Add Martin Kleppmann's lecture series to course resources

src/styles/main.css
=> feat(css): center Mermaid diagrams

content/index.md
=> [Meta] Fix email forwarading tutorial Notion link

content/sd/index.md
=> [SD] Update main page

content/ges/0004-informacao-financeira.md
The example solution refers to each instruction by number, which means an ordered list is needed rather than the current unordered one.
=> [Ges] Fix example typesetting

content/es/0004-refactoring-and-reuse.md
Os seguintes tipos de refactoring foram adicionados.
Test Driven Development
Litter-Pickup
Comprehension
Preparatory
Planned
Long-Term
=> [ES] add content to refactoring and reuse

content/es/0006-software-architecture.md
Os seguintes tópicos foram desenvolvidos
Views
Lógica (Logical view)
Física (Physical view)
Desenvolvimento (Development view)
Processo (Process view)
Padrões Arquiteturais
MVC
Layered
Repository
Client-Server
Pipe and Filter
Arquiteturas de Aplicações
Transaction Processing Systems
Information Systems
Language Processing Systems
Engenharia de Requisitos
Qualidades dos Requisitos
Processo de Engenharia de Requisitos
=> [ES] Add content to software architecture

content/cdi-iii/exercicios/0001-fichas-2021-2022.md, content/cdi-iii/exercicios/0003-fichas-2023-2024.md
=> [CDI-III] Add "Eq. Diferenciais Lineares de 1a ordem" exercises sheet

content/cdi-i/index.md
=> [CDI-I] Add link to Calculus Made Easy online book

content/al/index.md
=> [AL] Add link to immersive linear algebra online book

content/cdi-iii/0006-transformada-laplace.md
=> [CDI-III] Replace "x" with "t" in L.T integral equation

content/ia/0005-jogos.md
=> [IA] Fix typo in minimax algorithm ("melhor" -> "melhorar")

content/sd/0005-replicacao-e-tolerancia-a-faltas.md
Even though the explanation on the website is already good ([client-replica interaction](https://resumos.leic.pt/sd/replicacao-e-tolerancia-a-faltas/#intera%C3%A7%C3%A3o-cliente-r%C3%A9plica)), I felt that, like in the course book, the full algorithm written out in text form can still be a bit hard to follow. When I was studying for the exam, I wrote it out as pseudocode, and that helped me a lot.
The pseudocode is entirely based on the course book (pages 785-791), and I tried to follow the same style used for other algorithms in the book.
I split it into four parts to make it easier to read and understand:
* Envio de pedido de **leitura** (*query*) do cliente para a réplica
* Envio de pedido de **modificação** (*update*) do cliente para a réplica
* Troca de mensagens de **gossip** entre …
=> [SD] Add pseudocode for Gossip Architecture
