leic-pt/resumos-leic

src/md/0007-funcoesgeradoras.md, src/md/0009-combinatorio.md
seemed like `z(v(z))` was function `z` evaluated at `v(z)`, but it's just a product
=> [MD] add clarity + fix typo

src/cdi-ii/0015-extremos-condicionados.md
The cross product operator should be `\times`, not `\cdot`.
=> [CDI2] Fix cross product operator

src/md/0021-galeshapley.md
Changed 'Estalidade' to 'Estabilidade'.
=> [MD] Fix typo in 'Estailidade'

src/styles/main.css
Remove extra space from dark-mode-toggle button.
**Actual:**
**Fixed:**
=> Fix dark-mode-toggle extra space

content/cdi-iii/0002-sistemas-eq-lineares-coef-constantes.md
Esclarecer que o conjunto solução de uma EDO ter dimensão n (e portanto n vetores na base) não é o mesmo que ter n soluções.
=> [CDI3] Esclarecer diferença entre dimV = n e #V = n

content/cdi-iii/0010-serie-fourier.md
The value for `x=0` of an even extension is not zero, but the value of the function at `x=0`.
=> [CDI3] Fix definition for even extension of function

src/components/Dialog/Dialog.css, src/components/SearchBar/SearchBar.js, src/hooks/useViewHeightCSS.js
=> Fix search dialog being covered up by browser UI on mobile

content/ia/0004-satisfacao-restricoes.md
This section was mostly redundant because of the earlier section explaining AC-3
=> [IA] Remove global restrictions section

src/components/ThemeSettings.js, src/hooks/theme-hooks.js, src/styles/themes/black.css, src/styles/themes/nord.css, src/styles/themes/solarized.css
This PR does not include the UI to change the themes, only the code to load the correct theme.
To do that, you must change local storage manually, by setting the `theme-name` property, as such:
**Themes included** (in addition to the default themes):
All themes still respect the light/dark setting.
<details>
<summary>Screenshots</summary>
**Black**  
**Solarized Dark**  
**Solarized Light**  
**Nord Dark**
**Nord Light**
</details>
=> Add support for multiple themes

package.json
[`LICENSE.md`](https://github.com/leic-pt/resumos-leic/blob/d81c1ab0470c8a51de5cf584c4c64688381b0826/LICENSE.md) is GPL-3.0 but [`package.json#license`](https://github.com/leic-pt/resumos-leic/blob/d81c1ab0470c8a51de5cf584c4c64688381b0826/package.json#L21) is MIT: update the latter to match the former.
=> Update `package.json#license` field to match `LICENSE.md`

plugins/gatsby-remark-post-image-data/gatsby-browser.js, plugins/gatsby-remark-post-image-data/index.js, src/styles/main.css, src/styles/markdown.css
Left: Firefox, Right: Brave (Chromium)
This bug was introduced by #852, since the SVG rendered correctly before that (`<img>` vs `<object>`).
This PR aims to do a quick fix by adding an `onLoad` handler to the `<object>` elements, and replacing them with the inline SVG contents (it doesn't fetch the SVGs again, it uses the content already loaded by `<object>`).
=> Fix text not showing up correctly in complex SVGs in Chromium

.puppeteerrc.cjs, README.md
After #907, the site wouldn't build on Vercel if `node_modules` was cached.
This fixes that issue by allowing the Chromium browser downloaded by Puppeteer to be cached like before.
The environment variable `PUPPETEER_IN_PROJECT_DIRECTORY` must be set to a truth-y value (i.e. `1`) to turn on this (old) behavior.
=> Allow puppeteer to cache browser in project directory

package.json
Following #907, the minimum Node.js version required is no 18.
This adds an `engine` configuration to `package.json`, it order to give a more friendly error message.
=> Add engine to package.json to require Node 18

package.json, src/components/SearchBar/Highlight.js, src/components/SearchBar/Hit.js, src/components/ThemeSettings.js, src/hooks/theme-hooks.js, yarn.lock
This was unrelated to search.
It was related to unfocusing `<input>` elements, because this library https://github.com/donavon/use-event-listener was wrongfully adding a listener to window instead of the media query.
However, it seems like the culprit is Webpack, since the code of the library is correct and hasn't changed in years. Inspecting the code, we see it doesn't match before and after transpilation.
Introduced after #907
=> Fix site crashing on search

src/components/SearchBar/SearchModal.js
This PR fixes issue #774
Currently the following occurs:
- On change of search scope, the search query disappears
- On change of search scope, the result container does not show the appropriate result to reflect the change
- On change of search scope by clicking (i.e., not using key binding), the query input field loses focus
This PR addresses all of the above.
=> Fix the switching search scope bugs

content/pe/0009-teste-de-hipoteses.md
A distribuição qui-quadrado não é simetrica, logo os extremos dos intervalos tambem não são
=> [PE] Fix teste de hipoteses

flake.nix
The chromium binary puppeteer downloads isn't compatible with NixOS (for obvious reasons), so we need to use nixpkgs' version of chromium.
=> chore(nix flake): configure puppeteer to allow local build

content/cdi-i/0007-continuidade-limites.md
Na função Heaviside, já se verificara a continuidade em $x = \frac{1}{2}$ quando analisada em $x > 0$. 
A abcsissa a que se deveria referir é $x = 0$, não $\frac{1}{2}$.
=> [CDI-I] Fix typo on point continuity

content/sd/0003-tempo-e-sincronizacao.md
=> [SD] Enhance "Tempo e Sincronização" page

src/styles/main.css
Currently, the edit page link spans across the whole page content width, making it possible to hover/click on it where there's no icon/text:
This behavior is most likely undesired, so I propose setting its width to fit its content and docking it to the right (maintaining the old appearance/layout).
=> fix(style): set edit page link width to fit its content

src/components/ThemeSettings/DropdownSelect/DropdownOption.js, src/components/ThemeSettings/DropdownSelect/DropdownSelect.js, src/components/ThemeSettings/ThemeSettings.js, src/hooks/theme-hooks.js
I am submitting a pull request where I have made changes to the source code to enhance the font selection dropdown menu on the website. 
Now, each font name in the dropdown is displayed in its corresponding font style. 
This update makes the font selection process more intuitive and user-friendly, as users can see a preview of each font without having to test them one by one.
=> feat: display each font text with the corresponding font in theme settings

content/es/0002-unit-tests.md
Developed the information already present in the "Testes e Testes de Unidade" page of ES:
- Added a section on Automated Testing
- Added a section on Program Review and Inspections
- Developed the Test Doubles section
Redid the pull request as I forgot to commit the changes on a seperate branch.
Be sure to notify me in case you find typos or any other mistakes.
=> [ES] Improve "Testes e Testes de Unidade" page
